version: '3.7'
services:
  flask:
    image: webapp-flask
    build: ./web
    ports:
      - 9090:9090
    volumes:
      - "./:/run"
    networks: 
      - prodnetwork

  nginx:
    image: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask
    networks: 
      - prodnetwork
      
networks: 
  prodnetwork:
