version: '3.7'
services:
  flask:
    image: webapp-flask
    build: ./web
    ports:
      - 9090:9090
    depends_on: 
      - postgres
    volumes:
      - "./:/run"
    networks: 
      - prodnetwork

  nginx:
    image: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask
    networks: 
      - prodnetwork

  postgres:
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: production
    image: postgres:latest
    networks:
      - prodnetwork
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks: 
  prodnetwork:
